name: Baro Takvimini Guncelle

on:
  schedule:
    - cron: "0 0 1,15 * *" 
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gerekli Kütüphaneleri Yükle
        run: pip install requests beautifulsoup4

      - name: Takvim Güncelleme Scriptini Çalıştır
        run: python update.py

      - name: Yeni Takvimi Kaydet
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Dosya gerçekten indirildiyse Github'a yükle
          if [ -f baro_takvim.ics ]; then
            git add baro_takvim.ics
            git commit -m "Takvim güncellendi" || echo "Zaten güncel, değişiklik yok."
            git push || echo "Yükleme atlandı."
          else
            echo "Sitede yeni takvim bulunamadığı için yükleme yapılmadı."
          fi
